name: 'yq-ntd - portable yaml processor'
description: 'create, read, update, delete, merge, validate and do more with yaml'
branding:
  icon: arrow-up-circle
  color: blue
inputs:
  cmd:
    description: 'The Command which should be run'
    required: true
outputs:
  result:
    description: "The complete result from the yq command being run"
runs:
  using: 'docker'
  image: 'docker://885420015722.dkr.ecr.ap-southeast-1.amazonaws.com/os-base:yq-v4-githubaction'
  args:
    - ${{ inputs.cmd }}
